[build]
  command = "curl -fsSL https://github.com/quarto-dev/quarto-cli/releases/download/v1.4.557/quarto-1.4.557-linux-amd64.tar.gz -o quarto.tar.gz && tar -xzf quarto.tar.gz && export PATH=$PWD/quarto-1.4.557/bin:$PATH && quarto render"
  publish = "_site"
